[package]
name = "photo-tidier"
version = "0.1.0"
authors = ["MrKWatkins <mrkwatkins@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kamadak-exif = "^0.5.2"
once_cell = "^1.5.2"
structopt = "^0.3.13"